apiVersion: v1
items:
- apiVersion: v1
  kind: Service
  metadata:
    creationTimestamp: "2022-08-15T05:15:41Z"
    labels:
      app: nodeapp
    managedFields:
    - apiVersion: v1
      fieldsType: FieldsV1
      fieldsV1:
        f:metadata:
          f:labels:
            .: {}
            f:app: {}
        f:spec:
          f:externalTrafficPolicy: {}
          f:ports:
            .: {}
            k:{"port":3000,"protocol":"TCP"}:
              .: {}
              f:port: {}
              f:protocol: {}
              f:targetPort: {}
          f:selector:
            .: {}
            f:app: {}
          f:sessionAffinity: {}
          f:type: {}
      manager: kubectl
      operation: Update
      time: "2022-08-15T05:58:13Z"
    name: nodeapp
    namespace: app
    resourceVersion: "362042"
    uid: 11b05fbd-4ba1-40c3-b038-3100778c6274
  spec:
    clusterIP: 10.100.69.139
    clusterIPs:
    - 10.100.69.139
    externalTrafficPolicy: Cluster
    ipFamilies:
    - IPv4
    ipFamilyPolicy: SingleStack
    ports:
    - nodePort: 32210
      port: 3000
      protocol: TCP
      targetPort: 3000
    selector:
      app: nodeapp
    sessionAffinity: None
    type: NodePort
  status:
    loadBalancer: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
